name: arkham_horror_lcg_calculator
description: Chaos bag probability calculator for Arkham Horror LCG.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  path_provider: any
  json_serializable: any

flutter:
  uses-material-design: true
  fonts:
    - family: Birmingham
      fonts:
        - asset: assets/fonts/Birmingham.ttf
        - asset: assets/fonts/BirminghamBold.ttf
          weight: 700
  assets:
    - assets/icons/
    - assets/ui/
    - assets/images/